name: Build Capacitor iOS App

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Web Assets
        run: npm run build

      - name: Sync Capacitor iOS
        run: npx cap sync ios
        
      - name: Show Xcode version
        run: xcodebuild -version
        
      - name: Show Package.swift files
        run: |
          find . -name Package.swift -print
          
      - name: Show Resolved
        run: |
          find . -name Package.resolved -print
          
      
      - name: Show package resolution details
        run: |
          xcodebuild \
            -resolvePackageDependencies \
            -project ios/App/App.xcodeproj \
            -clonedSourcePackagesDirPath ./spm \
            -verbose

      - name: Build Unsigned Archive
        run: |
          xcodebuild archive \
            -project ios/App/App.xcodeproj \
            -scheme App \
            -configuration Release \
            -archivePath build/CameraLensApp.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            PROVISIONING_PROFILE_SPECIFIER=""

      - name: Package Unsigned IPA
        run: |
          mkdir Payload
          cp -r build/CameraLensApp.xcarchive/Products/Applications/*.app Payload/
          zip -r CameraLensApp.ipa Payload
    
      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-app
          path: CameraLensApp.ipa
